title: Giacomo Labbri # your name (or website title) here
logo: "/images/profile_image_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  2+ years as data analyst
  <br><br>
  Master in Physics
  <br><br>
  <a href="https://www.linkedin.com/in/giacomo-labbri/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
